Dont charge world startup
HSGamer/MoreFoWorld pull request #10
Opened 2024-10-21 20:27 UTC by Euphillya

On the Paper API, we can clearly see that the creation of the world should not be put at the start of the server. In addition to that, it breaks the World Generators which load just after the plugin.

2024-10-21 22:56 UTC, kaxlabs commented
I'm pretty sure due to the nature of how Folia works, it's supposed to be done on STARTUP. This plugin is basically a workaround for some of Folia's limitations.

2024-10-22 00:01 UTC, Euphillya commented
> I'm pretty sure due to the nature of how Folia works, it's supposed to be done on STARTUP. This plugin is basically a workaround for some of Folia's limitations.

On my Skyblock plugin where I use the same methods, it works great, especially if I want it to work on Paper too.

2024-10-22 05:28 UTC, HSGamer commented
You missed the case when you create a brand new world.
We would need to call `prepareLevels` and the `WorldLoadEvent` ourselves. Otherwise, it would hang and cause server crash. The original goal is to let Folia call them on its own so that we can be sure everything works correctly.
Simply changing the `load` order is not enough.

2024-10-22 05:28 UTC, HSGamer requested changes
You missed the case when you create a brand new world.
We would need to call prepareLevels and the WorldLoadEvent ourselves. Otherwise, it would hang and cause server crash. The original goal is to let Folia call them on its own so that we can be sure everything works correctly.
Simply changing the load order is not enough.

2024-10-22 10:36 UTC, HSGamer commented on src/main/java/me/hsgamer/morefoworld/WorldUtil.java
> +        io.papermc.paper.threadedregions.RegionizedServer.getInstance().addWorld(internal);
```suggestion
        console.prepareLevels(internal.getChunkSource().chunkMap.progressListener, internal);
        io.papermc.paper.threadedregions.RegionizedServer.getInstance().addWorld(internal);
```

2024-10-22 10:44 UTC, HSGamer approved these changes

2024-10-22 10:44 UTC, merged